
# MD010: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md010---hard-tabs
MD010:
  # Set code blocks to false so that code blocks will be ignored, default is true
  code_blocks: false

  