
# MD010: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md010---hard-tabs
MD010:
  # Set code blocks to false so that code blocks will be ignored, default is true
  code_blocks: false

# MD036 set to false to preserve the emphasis on deprecation notice on key-management.md (a heading is not necessary)
MD036: false

# MD028: set to false to allow blank line between blockquote: https://github.com/DavidAnson/markdownlint/blob/main/doc/md028.md
# This is because the blockquotes are shown separatedly (a deisred outcome) when having a blank line in between
MD028: false
